"LR": 1e-3
"WARMUP_UPDATES": 20
"NUM_ENVS": 128
"NUM_STEPS": 64
"EVAL_FREQ": 10
"TOTAL_TIMESTEPS": 10_000_000
"EVAL_TIMESTEPS": 2.5e7
"NUM_CHECKPOINTS": 1
"UPDATE_EPOCHS": 2
"NUM_MINIBATCHES": 8
"GAMMA": 0.9
"GAE_LAMBDA": 0.5
"CLIP_EPS": 0.1
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"FC_DIM_SIZE": 512
"HIDDEN_SIZE": 512
"ANNEAL_LR": True
"USE_LAYER_NORM": False
"LAMBDA_SCHEDULE": False

# "LR": 1e-3
# "WARMUP_UPDATES": 20
# "NUM_ENVS": 8
# "NUM_STEPS": 100
# "EVAL_FREQ": 10
# "TOTAL_TIMESTEPS": 100000
# "EVAL_TIMESTEPS": 2.5e7
# "NUM_CHECKPOINTS": 100
# "UPDATE_EPOCHS": 2
# "NUM_MINIBATCHES": 8
# "GAMMA": 0.9
# "GAE_LAMBDA": 0.5
# "CLIP_EPS": 0.1
# "SCALE_CLIP_EPS": False
# "ENT_COEF": 0.01
# "VF_COEF": 0.5
# "MAX_GRAD_NORM": 0.5
# "FC_DIM_SIZE": 512
# "HIDDEN_SIZE": 512
# "ANNEAL_LR": True
# "USE_LAYER_NORM": False
# "LAMBDA_SCHEDULE": False