defaults:
  - env: letter
  - learning: ippo-letter
  - ued: plr
  - _self_

"SEED": 2
"GROUP_NAME": "letter-plr"
"ENTITY": ""
"PROJECT": "letter"
"WANDB_MODE" : "online"
"SAVE_PATH": "checkpoints/new_letter"
"CHECKPOINT_SAVE_INTERVAL": 1
"run_name": "letter-plr-run"