defaults:
  - env: letter
  - learning: ippo-letter
  - _self_

"SEED": 2
"GROUP_NAME": "letter-sfl"
"ENTITY": ""
"PROJECT": "letter"
"WANDB_MODE" : "online"
"SAVE_PATH": "checkpoints/new_letter"

learning:
  "NUM_ENVS_FROM_SAMPLED": 32
  "NUM_ENVS_TO_GENERATE": 32

# SAMPLE LEARNABILITY 
"BATCH_SIZE": 4
"NUM_BATCHES": 20
"ROLLOUT_STEPS": 2
"NUM_TO_SAVE": 20
#"EVAL_SAMPLED_SET_PATH": "jax_multirobsim/deploy/data/sampled_test_set_100e_4a.pkl"
