defaults:
  - env: letter
  - learning: ippo-letter
  - _self_

"SEED": 2
"GROUP_NAME": "letter-sfl"
"ENTITY": ""
"PROJECT": "letter"
"WANDB_MODE" : "online"
"SAVE_PATH": "checkpoints/new_letter"

learning:
  "NUM_ENVS_FROM_SAMPLED": 64
  "NUM_ENVS_TO_GENERATE": 64

# SAMPLE LEARNABILITY 
"BATCH_SIZE": 5000
"NUM_BATCHES": 5
"ROLLOUT_STEPS": 2000
"NUM_TO_SAVE": 1000
#"EVAL_SAMPLED_SET_PATH": "jax_multirobsim/deploy/data/sampled_test_set_100e_4a.pkl"

# defaults:
#   - env: letter
#   - learning: ippo-letter
#   - _self_

# "SEED": 2
# "GROUP_NAME": "letter-sfl"
# "ENTITY": ""
# "PROJECT": "letter"
# "WANDB_MODE" : "online"
# "SAVE_PATH": "checkpoints/new_letter"

# learning:
#   "NUM_ENVS_FROM_SAMPLED": 4
#   "NUM_ENVS_TO_GENERATE": 4

# # SAMPLE LEARNABILITY 
# "BATCH_SIZE": 50
# "NUM_BATCHES": 5
# "ROLLOUT_STEPS": 200
# "NUM_TO_SAVE": 100
# #"EVAL_SAMPLED_SET_PATH": "jax_multirobsim/deploy/data/sampled_test_set_100e_4a.pkl"
