defaults:
  - env: minigrid
  - learning: ippo-minigrid
  - ued: plr
  - _self_

"SEED": 2
"GROUP_NAME": "minigrid-plr"
"ENTITY": "pamfil-1938844"
"PROJECT": "minigrid"
"WANDB_MODE" : "online"
"SAVE_PATH": "checkpoints/new_minigrid"
"CHECKPOINT_SAVE_INTERVAL": 0